### ISSUE TITLE
Move "Python 2.x" highlighter to "Python", and bring back "Python 3.x" highlighter

### ISSUE THREAD

**Issue by SoniEx2** [supakeen/pinnwand#60] opened 2020-03-05 14:22 UTC
One of the annoying things that's been annoying me since the change is that when I type "Python" my browser selects "Python 2.x" now, because that comes first, and then I need to scroll to get to "Python". It'd be nice if the Python 3.x highlighter was called "Python 3.x" so my browser would select it when I type "Python".

**Comment by supakeen** [comment] 2020-03-05 14:28
Related to this: https://github.com/supakeen/pinnwand/issues/45

**Comment by altendky** [comment] 2020-03-05 14:30
would a custom short list next to the full list be hard?  maybe even built from stats of still-alive pastes?  i have to wonder the last time someone actually wanted POVRay for example on bpaste.net

**Comment by altendky** [comment] 2020-03-05 14:46
side note, i thought shorter things generally sorted first so i was confused when i started noticing this as well.

```pycon
>>> sorted(['python 2.x', 'python'])
['python', 'python 2.x']
```

but the list is all over the place for python so i guess maybe it's some arbitrary order that pygments uses.

![image](https://user-images.githubusercontent.com/543719/75992047-6425f980-5ec5-11ea-9fce-16342481c553.png)

i think a short list could still be nice but perhaps separately we should (if it makes sense, i can do it) PR pygments about their order.

https://github.com/pygments/pygments/blob/a2d5f6b318d70d8d6a230cba46c8fc585efdaf1e/pygments/lexers/_mapping.py#L349-L354

```python3
    'PyPyLogLexer': ('pygments.lexers.console', 'PyPy Log', ('pypylog', 'pypy'), ('*.pypylog',), ('application/x-pypylog',)),
    'Python2Lexer': ('pygments.lexers.python', 'Python 2.x', ('python2', 'py2'), (), ('text/x-python2', 'application/x-python2')),
    'Python2TracebackLexer': ('pygments.lexers.python', 'Python 2.x Traceback', ('py2tb',), ('*.py2tb',), ('text/x-python2-traceback',)),
    'PythonConsoleLexer': ('pygments.lexers.python', 'Python console session', ('pycon',), (), ('text/x-python-doctest',)),
    'PythonLexer': ('pygments.lexers.python', 'Python', ('python', 'py', 'sage', 'python3', 'py3'), ('*.py', '*.pyw', '*.jy', '*.sage', '*.sc', 'SConstruct', 'SConscript', '*.bzl', 'BUCK', 'BUILD', 'BUILD.bazel', 'WORKSPACE', '*.tac'), ('text/x-python', 'application/x-python', 'text/x-python3', 'application/x-python3')),
    'PythonTracebackLexer': ('pygments.lexers.python', 'Python Traceback', ('pytb', 'py3tb'), ('*.pytb', '*.py3tb'), ('text/x-python-traceback', 'text/x-python3-traceback')),
```

python between pypy log and python2?

**Comment by supakeen** [comment] 2020-03-05 15:14
I've added the preferred_lexers configuration directive but also decided to sort the lexers by human name. Which makes the list clearer even when the lexer isn't in the preferred listing:

![image](https://user-images.githubusercontent.com/39536295/75995148-4aec6f80-5efc-11ea-814e-8841a6ab846b.png)

If you want to PR Pygments @altendky then go ahead, this local sort in my package seems to alleviate the initial problem.

**Comment by altendky** [comment] 2020-03-05 15:23
heh, that's a dict...  so at least until they drop 3.5 (/3.6) support it can't really be considered to be intended to indicate order.  :]  and as another example `get_all_lexers()` just tacks plugins onto the end further indicating no intention of sortedness.

https://github.com/pygments/pygments/blob/19721e8ff98304d0885c226fef3614d12525a945/pygments/lexers/__init__.py#L51-L58
```python3
def get_all_lexers():
    """Return a generator of tuples in the form ``(name, aliases,
    filenames, mimetypes)`` of all know lexers.
    """
    for item in LEXERS.values():
        yield item[1:]
    for lexer in find_plugin_lexers():
        yield lexer.name, lexer.aliases, lexer.filenames, lexer.mimetypes
```
so i think a sort here in pinnwand is appropriate when sorting is wanted.  at the moment i think a PR against pygments doesn't make much sense.  it sort of vaguely does, but...  not really.

**Comment by supakeen** [comment] 2020-03-05 15:59
I agree, I'll close this issue since the problem is "fixed". Now to think long and hard about what the preferred lexers will be for bpaste.

**Closed by supakeen** 2020-03-05 15:59 UTC
Labels: enhancement
